### ISSUE TITLE
RemoteConfig 관련

### ISSUE THREAD

**Issue by namenu** [green-labs/data-dev-interaction#3]
RemoteConfig 를 적극 활용하여 A/B 테스트 활성화하고자 합니다.

데이터 조직에서 먼저 실험이나 플래그를 제안할 수도 있고,
개발 조직에서 점진적 배포나 긴급 롤백을 위해 플래그를 제안할 수도 있습니다.

용도가 어쨌건, 피쳐플래그의 운영 주체는 데이터플랫폼팀이 되는 것이 적합하다고 생각합니다.
따라서 플래그 변경 또한 깃헙을 통해 요청하는 방법을 제안해봅니다.

--

참고로 최근 개발 과정에서 직접 생성하고 배포한 플래그가 3개 있습니다.

- `show_cart_button` : 장바구니 기능을 활성화할지 여부
- `farm_log_use_native` : 영농일지 RN 버전 사용 여부
   - https://greenlabs-group.slack.com/archives/C04MY6W0Q00/p1695027619518339
- `minigame/yut_20230919_prize_available` : 출석 후 윷놀이 이벤트 (20230919) 상금 가용 여부

**Comment by namenu** [comment]
@sangwoo-kim-greenlabs 앞으로 RemoteConfig 를 어떻게 관리하면 좋을지 고민이 됩니다.

플래그가 주렁주렁 달리는 것의 가장 큰 문제는 "플래그의 EOL 가 없어서 코드베이스에 기술부채가 쌓이는 것" 입니다.
따라서,

1) 어떤 목적의 플래그인지와
2) 플래그가 유효한 조건만

분명히 생성하면 큰 문제는 없어 보이긴 합니다.

그래서 위 조건을 명문화하는 공간으로 이 repo 를 생각해 보았습니다.

의견 부탁드립니다-

**Comment by sangwoo-kim-greenlabs** [comment]
옙. 팀내에 의견 우선 수렴해보겠습니다.

**Comment by namenu** [comment]
minigame/yut_20230919_prize_available => 21일 01:00시 false 로 변경
